### PR TITLE
feat: add ext-dom as requirement in composer.json

### PR DESCRIPTION
**Pull request by Chris53897**
This is needed by the use of \DOMElement
PhpStorm suggests to add it to composer.json to be sure it is available.

### CODE REVIEW

**Comment by Yozhef** [comment]
@Chris53897 can you please rebase in master?

**Comment by Chris53897** [comment]
I guess it is the best i wait until this is merged? https://github.com/FriendsOfBehat/MinkBrowserKitDriver/pull/8

**Comment by Yozhef** [comment]
@Chris53897 done)

**Comment by Chris53897** [comment]
This rebase looks wrong, i wil close this PR and make a new one

**Pull request closed without merging**
