### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
https://github.com/FriendsOfBehat/Mink/pull/2

**Comment by Yozhef** [comment]
https://github.com/FriendsOfBehat/driver-testsuite/pull/4

**Comment by pamil** [comment]
Could you rebase this PR? I've merged and released the related libraries :)

**Comment by pamil** [comment]
Okay, I've just restarted the build :)

**Comment by Yozhef** [comment]
Sorry, just opened the project =)

**Review by pamil — APPROVED** [review]

**Pull request merged**
